/**
 * Loads the P1–P10 picks of one F1 round collected outside the app (e.g. on WhatsApp),
 * so the round can then be scored in the app with "Importar resultado". Creates the
 * round from the calendar if it doesn't exist yet. Drivers are matched by surname
 * against the season's drivers, so load them first (admin screen, "Cargar calendario").
 *
 * Input JSON: { "season": "2026", "round": "GP Azerbaiyán", "picks": { "NAO": ["Russell", …] } }
 *
 *   npx tsx scripts/import-f1-picks.ts --in data/private/f1-baku.json --out data/private/f1-baku.sql \
 *     [--calendar data/private/f1-2026.json]
 *   npx supabase db query --linked -f data/private/f1-baku.sql
 */
import { readFileSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { F1_PICK_POSITIONS, f1SeasonRounds } from "../src/domain";
import { f1ExternalId, fetchF1Season, parseSchedule } from "../src/lib/jolpica";

interface PicksFile {
  season: string;
  round: string;
  picks: Record<string, string[]>;
}

const { values: args } = parseArgs({
  options: { in: { type: "string" }, out: { type: "string" }, calendar: { type: "string" } },
});

const sql = (value: string) => `'${value.replaceAll("'", "''")}'`;
const key = (name: string) => name.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().trim();

// Node scripts here compile to CommonJS, which has no top-level await.
async function main() {
  if (!args.in || !args.out) throw new Error("Usage: --in <picks.json> --out <picks.sql> [--calendar <schedule.json>]");
  const data = JSON.parse(readFileSync(args.in, "utf8")) as PicksFile;

  const races = args.calendar
    ? parseSchedule(JSON.parse(readFileSync(args.calendar, "utf8")))
    : (await fetchF1Season(data.season)).races;
  const plan = f1SeasonRounds(races).find((r) => key(r.name) === key(data.round));
  if (!plan) throw new Error(`Round "${data.round}" is not in the ${data.season} calendar.`);

  for (const [player, drivers] of Object.entries(data.picks)) {
    if (drivers.length !== F1_PICK_POSITIONS) throw new Error(`${player}: ${drivers.length} drivers, expected ${F1_PICK_POSITIONS}.`);
    if (new Set(drivers.map(key)).size !== drivers.length) throw new Error(`${player}: a driver is repeated.`);
  }

  const pickValues = Object.entries(data.picks)
    .flatMap(([player, drivers]) => drivers.map((driver, i) => `(${sql(player)}, ${i + 1}, ${sql(key(driver))})`))
    .join(",\n      ");
  const externalId = f1ExternalId(data.season, plan.raceRound, plan.kind);

  writeFileSync(
    args.out,
    `-- Generated by scripts/import-f1-picks.ts from ${args.in}
do $$
declare
  v_pool uuid := (select id from public.pools where sport = 'f1' and season = ${sql(data.season)});
  v_admin uuid := (select id from public.players where is_admin order by created_at limit 1);
  v_round uuid;
  v_status public.round_status;
  v_event uuid;
  v_missing text;
begin
  if v_pool is null then raise exception 'F1 pool % not found', ${sql(data.season)}; end if;

  select id, status into v_round, v_status from public.rounds
  where pool_id = v_pool and kind = ${sql(plan.kind)} and ordinal = ${plan.ordinal};
  if v_round is null then
    insert into public.rounds (pool_id, name, kind, ordinal)
    values (v_pool, ${sql(plan.name)}, ${sql(plan.kind)}, ${plan.ordinal})
    returning id into v_round;
  elsif v_status <> 'scheduled' then
    raise exception '% is already scored', ${sql(plan.name)};
  end if;

  select id into v_event from public.events where round_id = v_round limit 1;
  if v_event is null then
    insert into public.events (round_id, external_id, name, starts_at, lock_at)
    values (v_round, ${sql(externalId)}, ${sql(plan.name)}, ${sql(plan.startsAt.toISOString())}, ${sql(plan.lockAt.toISOString())})
    returning id into v_event;
  end if;

  create temp table import_picks on commit drop as
  select x.player, x.position, x.surname,
    (select p.id from public.players p where lower(coalesce(p.nickname, p.display_name)) = lower(x.player)) as player_id,
    (select array_agg(d.id) from public.f1_drivers d
     where d.season = ${sql(data.season)}
       and lower(translate(d.name, 'áéíóúüñÁÉÍÓÚÜÑ', 'aeiouunAEIOUUN')) like '% ' || x.surname) as driver_ids
  from (values
      ${pickValues}
  ) as x (player, position, surname);

  select string_agg(distinct player, ', ') into v_missing from import_picks where player_id is null;
  if v_missing is not null then raise exception 'Unknown players: %', v_missing; end if;
  select string_agg(distinct surname, ', ') into v_missing from import_picks
  where coalesce(array_length(driver_ids, 1), 0) <> 1;
  if v_missing is not null then
    raise exception 'Drivers not found (or ambiguous) — load the season''s drivers first: %', v_missing;
  end if;

  delete from public.f1_picks where event_id = v_event and player_id in (select player_id from import_picks);
  insert into public.f1_picks (event_id, player_id, position, driver_id, entered_by)
  select v_event, player_id, position, driver_ids[1], v_admin from import_picks;
end;
$$;
`,
  );
  console.log(`${plan.name}: pics de ${Object.keys(data.picks).length} jugadores · SQL en ${args.out}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
