/**
 * Imports one finished Liga MX / NFL round whose picks were collected outside the app
 * (e.g. on paper or WhatsApp): events with results, every player's picks, and the
 * scored results, computed with the same rules engine as the app.
 *
 * Input JSON: see data/private/*.json. Picks are one letter per event, in event order:
 * L = home (local), E = draw (empate), V = away (visitante), - = no pick.
 *
 *   npx tsx scripts/import-round.ts --in data/private/round.json --out data/private/round.sql \
 *     [--jackpot-balance 270000]   # only needed if someone had a perfect round
 *   npx supabase db query --linked -f data/private/round.sql
 */
import { readFileSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import {
  ligaMxRoundLock,
  nflGameLock,
  perfectRoundBonus,
  perfectRoundPoints,
  rankEntries,
  roundFinishedAt,
  scoreMatchPicks,
  settleRound,
  type MatchOutcome,
  type MatchResult,
  type Sport,
} from "../src/domain";

interface RoundFile {
  pool: { sport: Sport; season: string };
  round: { name: string; kind: string; ordinal: number };
  events: { externalId: string; home: string; away: string; startsAt: string; result: MatchResult | null }[];
  picks: Record<string, string>;
}

const { values: args } = parseArgs({
  options: { in: { type: "string" }, out: { type: "string" }, "jackpot-balance": { type: "string" } },
});
if (!args.in || !args.out) throw new Error("Usage: --in <round.json> --out <round.sql>");

const data = JSON.parse(readFileSync(args.in, "utf8")) as RoundFile;
if (data.pool.sport === "f1") throw new Error("F1 rounds use position picks; not supported by this script.");

const LETTERS: Record<string, MatchOutcome | undefined> = { L: "home", E: "draw", V: "away", "-": undefined };
const events = data.events.map((e, i) => ({ ...e, id: `e${i}`, startsAt: new Date(e.startsAt) }));

const picksByPlayer = Object.entries(data.picks).map(([player, letters]) => {
  if (letters.length !== events.length) {
    throw new Error(`${player}: ${letters.length} picks for ${events.length} events.`);
  }
  const picks: Record<string, MatchOutcome | undefined> = {};
  [...letters.toUpperCase()].forEach((letter, i) => {
    if (!(letter in LETTERS)) throw new Error(`${player}: unknown pick "${letter}".`);
    picks[events[i].id] = LETTERS[letter];
  });
  return { player, picks };
});

const entries = picksByPlayer.map(({ player, picks }) => ({
  profileId: player,
  points: scoreMatchPicks(events, picks),
}));
const scorable = perfectRoundPoints(data.pool.sport, events.map((e) => e.result));
const round = settleRound(entries, { maxPoints: scorable });

let bonusCents = 0;
if (round.perfectIds.length > 0) {
  if (!args["jackpot-balance"]) throw new Error("Perfect round found: pass --jackpot-balance (cents).");
  bonusCents = perfectRoundBonus(Number(args["jackpot-balance"]), round.perfectIds.length);
}

const positions = new Map<string, number>();
for (const group of rankEntries(entries)) for (const id of group.profileIds) positions.set(id, group.from);

const firstKickoff = new Date(Math.min(...events.map((e) => e.startsAt.getTime())));
const lockFor = (start: Date) =>
  data.pool.sport === "liga_mx" ? ligaMxRoundLock(firstKickoff) : nflGameLock(start);
const finishedAt = roundFinishedAt(data.pool.sport, events.map((e) => e.startsAt));

const sql = (value: string | null | undefined) => (value == null ? "null" : `'${value.replaceAll("'", "''")}'`);

const eventValues = events
  .map(
    (e, i) =>
      `(${i}, ${sql(e.externalId)}, ${sql(e.home)}, ${sql(e.away)}, ${sql(e.startsAt.toISOString())}::timestamptz, ` +
      `${sql(lockFor(e.startsAt).toISOString())}::timestamptz, ${sql(e.result)})`,
  )
  .join(",\n    ");

const pickValues = picksByPlayer
  .flatMap(({ player, picks }) =>
    events.flatMap((e, i) => (picks[e.id] ? [`(${sql(player)}, ${i}, ${sql(picks[e.id])})`] : [])),
  )
  .join(",\n    ");

const resultValues = entries
  .map((e) => {
    const bonus = round.perfectIds.includes(e.profileId) ? bonusCents : 0;
    return `(${sql(e.profileId)}, ${e.points}, ${positions.get(e.profileId)}, ${round.wonCents.get(e.profileId)}, ${bonus})`;
  })
  .join(",\n    ");

writeFileSync(
  args.out,
  `-- Generated by scripts/import-round.ts from ${args.in}
do $$
declare
  v_pool uuid := (select id from public.pools where sport = ${sql(data.pool.sport)} and season = ${sql(data.pool.season)});
  v_admin uuid := (select id from public.players where is_admin order by created_at limit 1);
  v_round uuid;
  v_missing text;
begin
  if v_pool is null then raise exception 'Pool not found'; end if;

  create temp table import_players on commit drop as
  select x.name, p.id as player_id
  from (values ${Object.keys(data.picks).map((p) => `(${sql(p)})`).join(", ")}) as x (name)
  left join public.players p on lower(coalesce(p.nickname, p.display_name)) = lower(x.name);

  select string_agg(name, ', ') into v_missing from import_players where player_id is null;
  if v_missing is not null then raise exception 'Unknown players: %', v_missing; end if;

  insert into public.rounds (pool_id, name, kind, ordinal, status, pot_cents, jackpot_cents, settlement_period_id)
  values (
    v_pool, ${sql(data.round.name)}, ${sql(data.round.kind)}, ${data.round.ordinal}, 'completed',
    ${round.potCents}, ${round.jackpotCents},
    (select id from public.settlement_periods
     where pool_id = v_pool and cutoff_at > ${sql(finishedAt.toISOString())}::timestamptz
     order by cutoff_at limit 1)
  )
  on conflict (pool_id, kind, ordinal) do update
    set name = excluded.name, status = excluded.status, pot_cents = excluded.pot_cents,
        jackpot_cents = excluded.jackpot_cents, settlement_period_id = excluded.settlement_period_id
  returning id into v_round;

  -- Re-running replaces the round's events, picks and results.
  delete from public.events where round_id = v_round;
  delete from public.round_results where round_id = v_round;

  create temp table import_events on commit drop as
  select x.idx, x.external_id, x.home, x.away, x.starts_at, x.lock_at, x.result, gen_random_uuid() as id
  from (values
    ${eventValues}
  ) as x (idx, external_id, home, away, starts_at, lock_at, result);

  insert into public.events (id, round_id, external_id, home_team, away_team, starts_at, lock_at, result)
  select id, v_round, external_id, home, away, starts_at, lock_at, result from import_events;

  insert into public.match_picks (event_id, player_id, selection, entered_by)
  select ie.id, ip.player_id, x.selection::public.match_outcome, v_admin
  from (values
    ${pickValues}
  ) as x (name, idx, selection)
  join import_players ip on ip.name = x.name
  join import_events ie on ie.idx = x.idx;

  insert into public.round_results (round_id, player_id, points, position, prize_cents, bonus_cents)
  select v_round, ip.player_id, x.points, x.position, x.prize, x.bonus
  from (values
    ${resultValues}
  ) as x (name, points, position, prize, bonus)
  join import_players ip on ip.name = x.name;
end;
$$;
`,
);

const pesos = (cents: number) => (cents / 100).toLocaleString("es-MX", { style: "currency", currency: "MXN" });
console.log(`${data.round.name}: ${scorable} partidos, bolsa ${pesos(round.potCents)}, al acumulado ${pesos(round.jackpotCents)}`);
for (const e of [...entries].sort((a, b) => b.points - a.points || a.profileId.localeCompare(b.profileId))) {
  const won = round.wonCents.get(e.profileId)!;
  console.log(`  ${String(positions.get(e.profileId)).padStart(2)}. ${e.profileId.padEnd(8)} ${e.points} pts${won ? `  ${pesos(won)}` : ""}`);
}
if (round.perfectIds.length) console.log(`Jornada perfecta: ${round.perfectIds.join(", ")} (${pesos(bonusCents)} c/u)`);
console.log(`Terminó ${finishedAt.toISOString()} · SQL en ${args.out}`);
